import { createAsyncThunk, createSlice, PayloadAction } from '@reduxjs/toolkit';
import { RootState, AppThunk } from '../../app/store';
import { apiGetCompanies } from './filterAPI';

export interface FilterState {
  companyOptions: string[];
  selectedCompanies: string[];
  status: 'idle' | 'loading' | 'failed';
}

const initialState: FilterState = {
  companyOptions: [],
  selectedCompanies: [],
  status: 'idle',
};

export const getCompanies = createAsyncThunk(
  'filter/getCompanies',
  async () => {
    const response = await apiGetCompanies();
    return response?.data || [];
  }
);

export const filterSlice = createSlice({
  name: 'filter',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    // Define a reducer for the selected companies
    changeSelectedCompanies: (state, action: PayloadAction<string[]>) => {
      console.log("selected", action.payload)
      state.selectedCompanies = action.payload;
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(getCompanies.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(getCompanies.fulfilled, (state, action) => {
        state.status = 'idle';
        console.log(action.payload)
        state.companyOptions = action.payload;
      })
      .addCase(getCompanies.rejected, (state) => {
        state.status = 'failed';
      });
  },
});

export const { changeSelectedCompanies } = filterSlice.actions;
export const companyOptions = (state: RootState) => state.filter.companyOptions;
export const selectedCompanies = (state: RootState) => state.filter.selectedCompanies;

export default filterSlice.reducer;
