import { createAsyncThunk, createSlice, PayloadAction } from '@reduxjs/toolkit';
import { stat } from 'fs';
import { RootState, AppThunk } from '../../app/store';
import { NewsItem } from './NewsScraper';
import { apiGetNews } from './newsScraperAPI';

export interface NewsState {
    news: NewsItem[];
    status: 'idle' | 'loading' | 'failed';
}

const initialState: NewsState = {
    news: [],
    status: 'idle',
};

export const getNews = createAsyncThunk(
    'newsScraper/getNews',
    async ({keyword, period}: {keyword: string, period: string}) => {
      const response = await apiGetNews(keyword, period);
      return response?.data || {};
    }
  );
  
export const newsScraperSlice = createSlice({
    name: 'news',
    initialState,
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {
    },
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    extraReducers: (builder) => {
        builder
        .addCase(getNews.pending, (state) => {
            state.status = 'loading';
        })
        .addCase(getNews.fulfilled, (state, action) => {
            state.status = 'idle';
            state.news = action.payload;
        })
        .addCase(getNews.rejected, (state) => {
            state.status = 'failed';
        })
    },
});

export const selectNews = (state: RootState) => state.newsScraper.news;

export default newsScraperSlice.reducer;